[package]
name = "homepage"
version = "0.2.7"
authors = ["James Kominick <james@kominick.com>"]

[dependencies]
error-chain = "0.11"
clap = "2"
env_logger = "0.5"
log = "0.4"
chrono = "0.4"
tera = "0.11"
lazy_static = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.4"

rouille = "2"

